/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infox.telas;

import br.com.infox.dal.ModuloConexao;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import java.sql.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author flavio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Connection conexao = null;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jMenuCad = new javax.swing.JMenu();
        jMenuCadCli = new javax.swing.JMenuItem();
        jMenuCadOs = new javax.swing.JMenuItem();
        jMenuCadUsu = new javax.swing.JMenuItem();
        jMenuRel = new javax.swing.JMenu();
        menRelCli = new javax.swing.JMenuItem();
        jMenuRelSer = new javax.swing.JMenuItem();
        jMenuAju = new javax.swing.JMenu();
        jMenuAjuSob = new javax.swing.JMenuItem();
        jMenuOpc = new javax.swing.JMenu();
        jMenuOpcSai = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("X - Sistema para Controle de Ordem de Serviçore");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jDesktop.setBackground(new java.awt.Color(118, 163, 234));
        jDesktop.setPreferredSize(new java.awt.Dimension(640, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/x.png"))); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblUsuario.setText("Usuário");

        lblData.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblData.setText("Data");

        jMenuCad.setText("Cadastro");

        jMenuCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadCli.setText("Cliente");
        jMenuCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadCliActionPerformed(evt);
            }
        });
        jMenuCad.add(jMenuCadCli);

        jMenuCadOs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadOs.setText("OS");
        jMenuCadOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadOsActionPerformed(evt);
            }
        });
        jMenuCad.add(jMenuCadOs);

        jMenuCadUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuCadUsu.setText("Usuários");
        jMenuCadUsu.setEnabled(false);
        jMenuCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadUsuActionPerformed(evt);
            }
        });
        jMenuCad.add(jMenuCadUsu);

        jMenu.add(jMenuCad);

        jMenuRel.setText("Relatório");
        jMenuRel.setEnabled(false);

        menRelCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        menRelCli.setText("Clientes");
        menRelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelCliActionPerformed(evt);
            }
        });
        jMenuRel.add(menRelCli);

        jMenuRelSer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuRelSer.setText("Serviços");
        jMenuRelSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelSerActionPerformed(evt);
            }
        });
        jMenuRel.add(jMenuRelSer);

        jMenu.add(jMenuRel);

        jMenuAju.setText("Ajuda");

        jMenuAjuSob.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        jMenuAjuSob.setText("Sobre");
        jMenuAjuSob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAjuSobActionPerformed(evt);
            }
        });
        jMenuAju.add(jMenuAjuSob);

        jMenu.add(jMenuAju);

        jMenuOpc.setText("Opções");

        jMenuOpcSai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuOpcSai.setText("Sair");
        jMenuOpcSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpcSaiActionPerformed(evt);
            }
        });
        jMenuOpc.add(jMenuOpcSai);

        jMenu.add(jMenuOpc);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblUsuario)
                    .addComponent(lblData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // as linha abaixo sibstituem a label lblData pela data atual do sistema ao iniciar o form
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));


    }//GEN-LAST:event_formWindowActivated

    private void jMenuOpcSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpcSaiActionPerformed
        // exibe uma caixa de diálogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            // a linha abaixo encerra o sistema
            System.exit(0);
        }


    }//GEN-LAST:event_jMenuOpcSaiActionPerformed

    private void jMenuAjuSobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAjuSobActionPerformed
       // Chamando a tela sobre
       TelaSobre sobre = new TelaSobre();
       sobre.setVisible(true);
    }//GEN-LAST:event_jMenuAjuSobActionPerformed

    private void jMenuCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadUsuActionPerformed
        // as linhas abaixo vão abrir o form TelaUsuario dentro do desktop pane
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        jDesktop.add(usuario);
    }//GEN-LAST:event_jMenuCadUsuActionPerformed

    private void jMenuCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadCliActionPerformed
        // chamar a tela de cliente
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        jDesktop.add(cliente);
    }//GEN-LAST:event_jMenuCadCliActionPerformed

    private void jMenuCadOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadOsActionPerformed
        // chamando a tela OS
        TelaOS os = new TelaOS();
        os.setVisible(true);
        jDesktop.add(os);
    }//GEN-LAST:event_jMenuCadOsActionPerformed

    private void menRelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelCliActionPerformed
        // gerando um relatorio de clientes
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão deste relatório?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
        //imprimindo relatório com o framework JasperReports (iReport)
        
            try {
                // usando a classe JasperPrint para preparar impressao de um relatorio
           JasperPrint print = JasperFillManager.fillReport("/home/flavio/reports/clientes.jasper", null, conexao);
           // a linha abaixo exibe o relatorio atraves da classe JasperViewer
           JasperViewer.viewReport(print, false);
            
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                 
            }
        
        }
    }//GEN-LAST:event_menRelCliActionPerformed

    private void jMenuRelSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelSerActionPerformed
        // gerando um relatorio de serviços
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão deste relatório?", "Atenção!", JOptionPane.YES_NO_OPTION);
        
        if(confirma == JOptionPane.YES_OPTION){
        
            // imprimindo relatorio com o framework JasperReports
            try {
                // Usando a classe JasperPrint para preparar a impressao de um ralatorio
                JasperPrint print = JasperFillManager.fillReport("/home/flavio/reports/servicos.jasper", null, conexao);
         JasperViewer.viewReport(print, false);
            } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
            }
        
        }
    }//GEN-LAST:event_jMenuRelSerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenuAju;
    private javax.swing.JMenuItem jMenuAjuSob;
    private javax.swing.JMenu jMenuCad;
    private javax.swing.JMenuItem jMenuCadCli;
    private javax.swing.JMenuItem jMenuCadOs;
    public static javax.swing.JMenuItem jMenuCadUsu;
    private javax.swing.JMenu jMenuOpc;
    private javax.swing.JMenuItem jMenuOpcSai;
    public static javax.swing.JMenu jMenuRel;
    private javax.swing.JMenuItem jMenuRelSer;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menRelCli;
    // End of variables declaration//GEN-END:variables
}
